pipeline {
    agent any
    tools {
        go 'go-1.19'
    }

    stages {
        stage('Unit test backend') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }

            }
        }
    }
}
