pipeline {
    agent any

    stages {
        stage('Unit Tests -  Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reusdeNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }

            }
        }

        stage('Unit Tests - Frontend')
        agent{
            docker {
                image 'node:20-alpine'
                resuseNode true

            }
        }
        steps {
            dir('bugtracker-frontend') {
                sh ''' 
                npm ci
                npm test
                '''
            }
        }

    }
}
